name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove esta linha se desejar publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Para adicionar assets ao seu aplicativo, adicione uma seção de assets, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Um asset de imagem pode se referir a uma ou mais "variantes" específicas de resolução, veja
  # https://flutter.dev/to/resolution-aware-images

  # Para detalhes sobre como adicionar assets de dependências de pacotes, veja
  # https://flutter.dev/to/asset-from-package

  # Para adicionar fontes personalizadas ao seu aplicativo, adicione uma seção de fontes aqui,
  # nesta seção "flutter". Cada entrada nesta lista deve ter uma chave "family"
  # com o nome da família da fonte e uma chave "fonts" com uma lista contendo
  # o asset e outros descritores para a fonte. Por exemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para detalhes sobre fontes de dependências de pacotes,
  # veja https://flutter.dev/to/font-from-package
